// <auto-generated />
using System;
using KontrolinisDarbas.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KontrolinisDarbas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240826163238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KontrolinisDarbas.Models.Pirkejas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ElPastas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numeris")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pirkejas");
                });

            modelBuilder.Entity("KontrolinisDarbas.Models.Produktas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Kaina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kiekis")
                        .HasColumnType("int");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Produktas");
                });

            modelBuilder.Entity("KontrolinisDarbas.Models.Uzsakymas", b =>
                {
                    b.Property<int>("PirkejoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PirkejoId"));

                    b.Property<int>("PirkejasId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktasId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UzsakymoDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UzsakymoId")
                        .HasColumnType("int");

                    b.Property<int>("UzsakymoKiekis")
                        .HasColumnType("int");

                    b.HasKey("PirkejoId");

                    b.HasIndex("PirkejasId");

                    b.HasIndex("ProduktasId");

                    b.ToTable("Uzsakymas");
                });

            modelBuilder.Entity("KontrolinisDarbas.Models.Uzsakymas", b =>
                {
                    b.HasOne("KontrolinisDarbas.Models.Pirkejas", "Pirkejas")
                        .WithMany()
                        .HasForeignKey("PirkejasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KontrolinisDarbas.Models.Produktas", "Produktas")
                        .WithMany()
                        .HasForeignKey("ProduktasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pirkejas");

                    b.Navigation("Produktas");
                });
#pragma warning restore 612, 618
        }
    }
}
